### ISSUE TITLE
Could you please update example scripts in 'notebooks'?

### ISSUE THREAD

**Issue by jimmy-1112** [materialsvirtuallab/mlearn#25]
Could you please update example scripts in 'notebooks'?

I downloaded this package on Dec. 4, 2019 & successfully installed various descriptors (except for MTP which needs a license from the author).  However, when I tried to run the examples scripts in the directory 'notebooks', I found they were kind of obsolete.  For instant, to import the GAP potential, it is written in the script as "from mlearn.potential.gap import GAPotential".  While I checked the location of 'mlearn' package, and the folder has already been renamed from 'potential' to 'potentials'.  There are more incompatibilities like this.  Accordingly, the example scripts cannot even be ran.  

As a beginner, I'm so grateful that your teams can share such a handy tool to run various machine learning potentials.  But I think it is really important for us to follow the example scripts, since there is no full documentation with respect to this tool available online.

Many thanks!

**Comment by YunxingZuo** [comment]
Hi @jimmy-1112 

Thanks for the interest! As you mentioned, the examples were obsolete partly because of the change of module names., while they were also incompatible due to some minor changes in the original packages (e.g., some keywords were added to the n2p2). I have updated the examples. Pls let me know if you meet any other bugs when running the new examples. We are happy to help any users throughout their questions.

**Comment by jimmy-1112** [comment]
> Hi @jimmy-1112
> 
> Thanks for the interest! As you mentioned, the examples were obsolete partly because of the change of module names., while they were also incompatible due to some minor changes in the original packages (e.g., some keywords were added to the n2p2). I have updated the examples. Pls let me know if you meet any other bugs when running the new examples. We are happy to help any users throughout their questions.

Dear Yunxing,

Thanks so much for your prompt reply and bug-fixing.
However, I encountered another errors after I pulled the new version and ran the example scripts again. The error logs are similar for both GAP & N2P2:

"FileNotFoundError: [Errno 2] No such file or directory: '/home/.conda/envs/ase/lib/python3.7/site-packages/mlearn-0.1.0-py3.7.egg/mlearn/potentials/params/GAP.json'“
"FileNotFoundError: [Errno 2] No such file or directory: '/home/.conda/envs/ase/lib/python3.7/site-packages/mlearn-0.1.0-py3.7.egg/mlearn/potentials/params/NNinput.json'"

I did nothing to the scripts, just opened them with Jupyter-Notebook and ran them cell by cell.
These errors were obtained when running the 2nd cell, i.e. '_Set up the NNP and train_'.

I guessed the 'data.json' file might be the input file required to load instead of 'GAP.json' or 'NNinput.json'.  But I really have no idea about how to invoke these files.

Could you please help in giving more advices?  
Again, I'm so grateful for your swift reply.
Many thanks.

Best wishes,
Qiangshun Guan (Jimmy)

**Comment by jimmy-1112** [comment]
> > Hi @jimmy-1112
> > Thanks for the interest! As you mentioned, the examples were obsolete partly because of the change of module names., while they were also incompatible due to some minor changes in the original packages (e.g., some keywords were added to the n2p2). I have updated the examples. Pls let me know if you meet any other bugs when running the new examples. We are happy to help any users throughout their questions.
> 
> Dear Yunxing,
> 
> Thanks so much for your prompt reply and bug-fixing.
> However, I encountered another errors after I pulled the new version and ran the example scripts again. The error logs are similar for both GAP & N2P2:
> 
> "FileNotFoundError: [Errno 2] No such file or directory: '/home/.conda/envs/ase/lib/python3.7/site-packages/mlearn-0.1.0-py3.7.egg/mlearn/potentials/params/GAP.json'“
> "FileNotFoundError: [Errno 2] No such file or directory: '/home/.conda/envs/ase/lib/python3.7/site-packages/mlearn-0.1.0-py3.7.egg/mlearn/potentials/params/NNinput.json'"
> 
> I did nothing to the scripts, just opened them with Jupyter-Notebook and ran them cell by cell.
> These errors were obtained when running the 2nd cell, i.e. '_Set up the NNP and train_'.
> 
> I guessed the 'data.json' file might be the input file required to load instead of 'GAP.json' or 'NNinput.json'. But I really have no idea about how to invoke these files.
> 
> Could you please help in giving more advices?
> Again, I'm so grateful for your swift reply.
> Many thanks.
> 
> Best wishes,
> Qiangshun Guan (Jimmy)

Dear Yunxing,

I found the previous problem was also due to the obsolete package distribution.

I did some minor changes and am currently able to run the N2P2 example script.  Specifically, I just copied two folders from your github repository to the directory of the installed python module:

(1) Copy 'mlearn/mlearn/potentials/params' to '~/.conda/envs/ase/lib/python3.7/site-packages/mlearn-0.1.0-py3.7.egg/mlearn/potentials' 
(2) Copy 'mlearn/mlearn/potentials/lammps/templates' to '~/.conda/envs/ase/lib/python3.7/site-packages/mlearn-0.1.0-py3.7.egg/mlearn/potentials/lammps' 

While, as for GAP, there was one more error with respect to locating the 'train.xml' file as " FileNotFoundError: [Errno 2] No such file or directory: 'train.xml' ".  However, I could not find any train.xml file in your repository. 

Thanks and looks forward to your reply.

Best wishes,
Jimmy

**Comment by YunxingZuo** [comment]
Dear Jimmy,

Could you try the code in the following code in the notebook:

```
from pymatgen import Structure
from monty.serialization import loadfn
from mlearn.data import pool_from
from mlearn.potentials.gap import GAPotential

data = loadfn('data.json')
train_structures = [d['structure'] for d in data]
train_energies = [d['outputs']['energy'] for d in data]
train_forces = [d['outputs']['forces'] for d in data]

# write the training data file

gap = GAPotential()
atoms_filename = 'train.xyz'
train_pool = pool_from(train_structures, train_energies, train_forces)
gap.write_cfgs(filename=atoms_filename, cfg_pool=train_pool)
```

And then run the following command in the terminal:
```
teach_sparse at_file=train.xyz gap={soap l_max=8 n_max=8 atom_sigma=0.5 zeta=4 cutoff=5.0 cutoff_transition_width=0.5 delta=1.0 f0=0.0 n_sparse=200 covariance_type=dot_product sparse_method=cur_points} sparse_jitter=1e-08 e0=-0.97 e0_offset=0.0 default_sigma={0.0005 0.1 0.05 0.01} energy_parameter_name=dft_energy force_parameter_name=dft_force gp_file=train.xml
```

Check whether there is a file named ```train.xml```? This is the essential work that the gap.train method does in the example notebook. If there is no such file, the problem might be in the installed QUIP package, which may need further troubleshooting.

**Comment by YuTingLiu33** [comment]
Dear Yunxing，
I also found the same problem as Jimmy when run the GAP example:[Errno 2] No such file or directory: 'train.xml'
 I try the code in the notebook. The return is The teach-sparse program is now called gap_fit,so I replace teach-sparse with gap_fit. There is no error interminal.Idon't know how to solve the problem.
And when I run the examples of MTP and NNP ,errors also occurred.
The MTP is [Errno 2] No such file or directory: '/home/xianbin/software/anaconda3/lib/python3.7/site-packages/mlearn/potentials/params/08g.mtp' .
And NNP reported errors in the terminal
1) gsl: init.c:33: ERROR: histogram length n must be positive integer
Default GSL error handler invoked.
2)terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR: Keyword "jacobian_mode" not found.

Thanks and looks forward to your reply.

Best wishes,
Yuting

**Comment by YunxingZuo** [comment]
Hi @jimmy-1112 @YuTingLiu33 

Please update the package. Some modifications were added to make the package compatible with the newer versions of GAP and NNP. These fixes should address the running errors of the examples. Please let me know if you meet any further problems.

Yunxing

**Comment by YuTingLiu33** [comment]
Dear Yunxing,
I have updated the package and run the examples.Now all the example scripts can run without errors except MTP.Thank you for your prompt reply.

Best wishes,
Yuting

**Comment by jimmy-1112** [comment]
> Hi @jimmy-1112 @YuTingLiu33
> 
> Please update the package. Some modifications were added to make the package compatible with the newer versions of GAP and NNP. These fixes should address the running errors of the examples. Please let me know if you meet any further problems.
> 
> Yunxing

Dear Yunxing,

Thanks so much for your help and kind sharing.
I have reinstalled the new package & tested the scripts.
For GAP & NNP, no errors were found.
While, for SNAP & qSNAP, the errors were shown as:

"  File /home/Public/0001_mlearn/mlearn/potentials/lammps/calcs.py", line 120, in calculate
    raise RuntimeError(error_msg)
RuntimeError: LAMMPS exited with return code 1ERROR: Illegal compute sna/atom command (../compute_sna_atom.cpp:107), Last command: compute        sna all sna/atom 1 0.99363 6 2.5 1 diagonal 3 rmin0 0 quadraticflag 0 bzeroflag 0  "

I guess this is because of the incompatiblity with LAMMPS, which I'm currently using is lammps-Aug07-2019.  Could you please tell which version of LAMMPS is the best fit for your tool?

Many thanks, again.

Best wishes,
Jimmy

**Comment by YunxingZuo** [comment]
@jimmy-1112 Please refer to the latest stable version of LAMMPS 2018. This can be found in [LAMMPS-12Dec2018](https://github.com/lammps/lammps/releases/tag/stable_12Dec2018).

**Comment by chc273** [comment]
@jimmy-1112 did you install “snap” in lammps by “make yes-snap” before comipiling lammps? Snap was not included in lammps by default last time I checked. Check our snap repo for details. Thanks https://github.com/materialsvirtuallab/snap

**Comment by jimmy-1112** [comment]
> @jimmy-1112 Please refer to the latest stable version of LAMMPS 2018. This can be found in [LAMMPS-12Dec2018](https://github.com/lammps/lammps/releases/tag/stable_12Dec2018).

Dear Yunxing,

Thanks so much for your reply.
I reinstall the lammps package as what you suggested.
And GAP, NNP, SNAP & qSNAP can work well now.

**Comment by jimmy-1112** [comment]
> @jimmy-1112 did you install “snap” in lammps by “make yes-snap” before comipiling lammps? Snap was not included in lammps by default last time I checked. Check our snap repo for details. Thanks https://github.com/materialsvirtuallab/snap

Dear Chi Chen,

I'm pretty sure I compile lammps with 'make yes-SNAP' and I have tested the example scripts in 'lammps/examples/snap'.  I have reinstalled lammps-stable-12Dec2018, and now all of GAP, NNP, SNAP & qSNAP can work well. 

Thanks so much for your comment and all of your effort for this free package.

Best wishes!
