### ISSUE TITLE
Cu dataset question 

### ISSUE THREAD

**Issue by lmj1029123** [materialsvirtuallab/mlearn#3]
Hi, 

I am trying to reproduce the result for the Cu dataset and I have several questions about it. In the input.nn file, in the atom_energy,  it is "Cu -0.97". What is the meaning of it? The energy of each Cu atom is subtracted by 0.97 eV or Hartree? Also, I am wondering which standardization scheme is used for the fingerprints. 

fp = (fp - fp_min)/(fp_max - fp_min) or something else?

Thanks!

Mingjie

**Comment by YunxingZuo** [comment]
@lmj1029123 Hi!

The "atom energy" is a keyword in the original package [n2p2](https://compphysvienna.github.io/n2p2/Topics/keywords.html). Basically, it shifts the total potential energy by 0.97 Hartree for each Cu atom. As you may see in input.nn file, the "scale_min_short" and "scale_max_short" determine the standardization scheme. The "scale_min_short = 0.0" and "scale_max_short = 1.0" mean to scale the fingerprints into the range of (0, 1), which is exactly fp = (fp - fp_min)/(fp_max - fp_min).

Yunxing

**Comment by lmj1029123** [comment]
Thanks a lot for the reply. I am wondering whether there is the train.log file so I can know the exact order of the symmetry functions fed into the NN. Thank you very much!

**Comment by lmj1029123** [comment]
I think I get it thanks
