### ISSUE TITLE
The unit of virial stress Si data set

### ISSUE THREAD

**Issue by yanxon** [materialsvirtuallab/mlearn#64]
Hello,

What is the unit of the virial stress Si data set? Also, for each structure, the virial stress has 6 members. How are these members organized?

Thank you for your help in advance.

**Comment by YunxingZuo** [comment]
The units of the virial_stress in our database is kilobar (kB), the order is [xx, yy, zz, xy, yz, xz].

**Comment by yanxon** [comment]
@YunxingZuo 

Thank you for your prompt response. I really appreciate it.
